name: Element.Delegates
author: astolwijk
current: 0.1
category: Native
tags: [Events,Delegation,Elements]
#demo: http://www.aryweb.nl/projects/animateimage/
#docs: http://github.com/arian/animateImage/blob/master/README.md