name: Element.Delegates
author: astolwijk
current: 0.2
category: Native
tags: [Event,Events,Delegation,Elements]
demo: http://www.aryweb.nl/projects/eventdelegation/
docs: http://github.com/arian/Element.Delegation/blob/master/README.md